name: Quality Gates

on:
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install
        name: Install

      - run: npm run test --max-workers ${{ steps.cpu-cores.outputs.count }}
        name: Test